FROM ubuntu:18.04

RUN apt-get update

RUN apt-get --assume-yes install curl make libnuma1

# required for CPM:
RUN apt-get --assume-yes install git zip unzip sqlite3

# required for KiCS2
RUN apt-get --assume-yes install ghc ghc-prof cabal-install rlwrap
    
RUN rm -rf /var/lib/apt/lists/*

# just to be sure
ENV LANG C.UTF-8

# copy, unpack and install kics2
WORKDIR /kics2
RUN curl -sSL -o kics2.tar.gz https://www-ps.informatik.uni-kiel.de/kics2/download/kics2-2.2.0.tar.gz
RUN tar xvzf kics2.tar.gz
RUN rm kics2.tar.gz
RUN mv kics2-2.2.0 kics2
WORKDIR /kics2/kics2
ENV PATH /kics2/kics2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN make

ENV HOME /userhome
RUN mkdir -p  $HOME
RUN chmod 777 $HOME

RUN mkdir /kics2/cpm

ENV PATH /kics2/kics2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# options for CPM so that tools will be installed in /kics2/cpm
ENV CPMOPTS="-d REPOSITORY_PATH=/kics2/cpm/index -d PACKAGE_INSTALL_PATH=/kics2/cpm/packages -d APP_PACKAGE_PATH=/kics2/cpm/app_packages -d BIN_INSTALL_PATH=/kics2/cpm/bin"

RUN bin/cypm $CPMOPTS update
RUN bin/cypm $CPMOPTS install importusage
RUN bin/cypm $CPMOPTS install showflatcurry
RUN bin/cypm $CPMOPTS install currypp
RUN bin/cypm $CPMOPTS install currycheck
RUN bin/cypm $CPMOPTS install currydoc

# set path with cpm bin directory included
ENV PATH /kics2/cpm/bin:/kics2/kics2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# pre-compile libraries used by curry-check
COPY CheckExample.curry .
RUN /kics2/cpm/bin/curry-check CheckExample

# make tool files readable
RUN chmod -R go+rX /kics2/cpm/app_packages

# install a patched version of bin/kics2
# (necessary due to aynchronous terminal setting problems with rlwrap/docker,
# see https://github.com/moby/moby/issues/28009)
COPY kics2.sh /kics2/kics2/bin/kics2
RUN chmod 755 /kics2/kics2/bin/kics2

ENTRYPOINT ["/kics2/kics2/bin/kics2"]
